import React from 'react';
import { ShieldCheck, Users, Star, Plane, WalletCards, CalendarDays, ArrowUpRight, Package, ReceiptText, ContactRound, CheckCircle2, FileUp, UserPlus, CreditCard } from 'lucide-react';
import KpiGrid from '../components/KpiGrid'; import CrmPipeline from '../components/CrmPipeline'; import RevenuePanel from '../components/RevenuePanel'; import {kpis,pipeline,transactions,departures} from '../data/dashboard';
const status=[['Prospek','342'],['Booking','286'],['DP','248'],['Pelunasan','198'],['Siap Berangkat','142'],['Berangkat','68']];
export default function DashboardPage(){const now=new Date();const masehi=new Intl.DateTimeFormat('id-ID',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(now);let hijri='';try{hijri=new Intl.DateTimeFormat('id-ID-u-ca-islamic-umalqura',{day:'numeric',month:'long',year:'numeric'}).format(now)}catch{hijri='Kalender Hijriah'}return <section className="content dashboard-mdd">
<div className="dashboard-welcome"><div><div className="dashboard-date"><CalendarDays/> <span>{masehi} • {hijri}</span></div><h2>Assalamu'alaikum, Abu Adzka</h2><p>Berikut ringkasan performa Travel Umrah MDD hari ini.</p></div></div><section className="mdd-hero"><div className="hero-copy"><span>Selamat Datang di</span><h1><b>MARKAZ DAKWAH DIGITAL</b></h1><p>Melayani perjalanan ibadah ke Baitullah dengan amanah, profesional dan penuh berkah.</p><div className="hero-values"><span><ShieldCheck/>Amanah</span><span><Users/>Profesional</span><span><Star/>Penuh Berkah</span></div></div><div className="hero-emblem islamic-arch"><div className="arabic">لَبَّيْكَ اللَّهُمَّ لَبَّيْك</div><small>LABBAIKALLAAHUMMA LABBAIK</small></div></section>
<div className="mobile-greeting"><img src="/travelumroh/abu-adzka-profile.jpg" alt="Abu Adzka"/><div><small>Assalamu'alaikum</small><b>Abu Adzka</b></div></div>
<KpiGrid items={kpis}/>
<div className="mobile-shortcuts"><a href="#/jamaah"><Users/><span>Jamaah</span></a><a href="#/paket"><Package/><span>Paket</span></a><a href="#/booking"><ReceiptText/><span>Booking</span></a><a href="#/keberangkatan"><Plane/><span>Keberangkatan</span></a><a href="#/pembayaran"><WalletCards/><span>Pembayaran</span></a><a href="#/crm"><ContactRound/><span>CRM & Leads</span></a></div>
<div className="reference-grid"><RevenuePanel/><article className="panel jamaah-status"><div className="title"><h3>Status Jamaah</h3></div><div className="status-wrap"><div className="donut"><strong>1.284</strong><small>Jamaah</small></div><div className="status-legend">{status.map((x,i)=><div key={x[0]}><i className={'dot d'+i}/><span>{x[0]}</span><b>{x[1]}</b></div>)}</div></div></article></div>
<div className="lower-grid"><CrmPipeline items={pipeline}/></div><div className="after-pipeline-grid"><article className="panel nearest"><div className="title"><h3>Keberangkatan Terdekat</h3><a href="#/keberangkatan">Lihat Semua <ArrowUpRight size={14}/></a></div>{departures.map((r,i)=><div className="trip" key={r[0]}><div className="trip-thumb">{i===0?'🕌':'🕋'}</div><span><b>{r[1]}</b><small><CalendarDays/> {r[0]} · {r[2]} Jamaah</small></span><em>{i===1?'Full':'H-'+(95+i*50)}</em></div>)}</article><article className="panel activity"><div className="title"><h3>Aktivitas Terbaru</h3><a href="#/laporan">Lihat Semua <ArrowUpRight size={14}/></a></div><div><CheckCircle2/><span><b>Pembayaran diverifikasi</b><small>5 menit lalu</small></span></div><div><UserPlus/><span><b>Jamaah baru terdaftar</b><small>12 menit lalu</small></span></div><div><FileUp/><span><b>Dokumen paspor diupload</b><small>28 menit lalu</small></span></div><div><CreditCard/><span><b>Booking baru</b><small>35 menit lalu</small></span></div></article></div>
<div className="grid dashboard-lists"><article className="panel"><div className="title"><h3>Transaksi Terbaru</h3><a href="#/pembayaran">Lihat Semua <ArrowUpRight size={14}/></a></div><table><tbody>{transactions.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></article></div>
</section>}