import React from 'react';
import { Activity, AlertTriangle, BarChart3, Banknote, Boxes, CalendarDays, CircleDollarSign, ClipboardList, GitCompareArrows, Megaphone, Plane, RefreshCw, Target, TrendingUp, Users } from 'lucide-react';
const empty='Belum ada data';
const kpis=[['OMZET',CircleDollarSign,'blue'],['TARGET',Target,'gold'],['CASH IN',Banknote,'green'],['OUTSTANDING',ClipboardList,'red'],['JAMAAH',Users,'blue'],['KEBERANGKATAN',Plane,'purple']];
const exec=[['Revenue',BarChart3],['Target Achievement',Target],['Leads',Users],['Booking',CalendarDays],['Show Up',Users],['Treatment',Activity],['Referral',RefreshCw],['Ad Spend',Megaphone],['ROAS',TrendingUp],['Top Campaign',TrendingUp],['Top Treatment',Target],['Stok Inventory Kritis',Boxes]];
const journey=[['Leads',Users,'blue'],['Prospek',Users,'gold'],['Booking',ClipboardList,'gold'],['Show Up',Users,'green'],['Keberangkatan',Plane,'purple'],['Rebooking',RefreshCw,'purple']];
const leadSources=['Google Ads','Meta Ads','TikTok Ads','Website','Referal','Offline','Lainnya'];
const alerts=[['Follow Up','CRM'],['No Show','Operasional'],['Stok Menipis','Inventory'],['Konten Belum Publish','Marketing'],['Input Terlambat','Semua Divisi']];
function Title({icon:Icon,title,sub}){return <div className="ref-title"><span><Icon/></span><div><h3>{title}</h3><p>{sub}</p></div></div>}
function dateLabels(){const d=new Date();const greg=new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'long',year:'numeric'}).format(d);let hijri='';try{hijri=new Intl.DateTimeFormat('id-ID-u-ca-islamic',{day:'numeric',month:'long',year:'numeric'}).format(d).replace(/H$/,'H');}catch{hijri='Tanggal Hijriah';}return {greg,hijri}}
function KaabaTawaf(){return <div className="ref-kaaba-scene" aria-label="Visual Ka'bah dan jamaah tawaf"><div className="ref-mosque-light"/><div className="ref-kaaba-real"><i className="kiswah-band"/><i className="kaaba-door"/><i className="kaaba-corner"/></div><div className="ref-tawaf-ring ring1">{Array.from({length:18},(_,i)=><i key={i} style={{'--i':i}}/>)}</div><div className="ref-tawaf-ring ring2">{Array.from({length:24},(_,i)=><i key={i} style={{'--i':i}}/>)}</div><div className="ref-floor"/></div>}
export default function DashboardPage(){const {greg,hijri}=dateLabels();return <section className="content dashboard-mdd owner-dashboard owner-reference">
 <header className="ref-hero"><div className="ref-ornament">✦</div><div className="ref-hero-copy"><h1>DASHBOARD OWNER</h1><div className="ref-date"><b>{greg}</b><span>{hijri}</span></div><p>Pusat Kontrol, Keputusan, dan Pertumbuhan Bisnis</p></div><KaabaTawaf/></header>
 <div className="ref-kpis">{kpis.map(([t,I,c])=><article className={`ref-kpi ${c}`} key={t}><span className="ref-kpi-icon"><I/></span><div><b>{t} ⓘ</b><p>{t==='TARGET'?'Belum ada target':empty}</p><i/></div><BarChart3 className="ref-mini-chart"/></article>)}</div>
 <div className="ref-top-grid"><article className="ref-panel executive"><Title icon={Target} title="OWNER EXECUTIVE OVERVIEW" sub="Ringkasan performa utama bisnis MDD Travel Haji & Umrah"/><div className="ref-exec-grid">{exec.map(([t,I])=><div className="ref-exec-item" key={t}><span><I/></span><div><b>{t}</b><small>{t==='Target Achievement'?'Belum ada target':empty}</small></div></div>)}</div></article><article className="ref-panel tower"><Title icon={Activity} title="OWNER CONTROL TOWER" sub="Kondisi bisnis harian dan bulan berjalan"/><div className="ref-chart-legend"><i/>Omzet <i/>Booking <i/>Show Up <i/>Keberangkatan</div><div className="ref-chart"><div className="ref-bars">{[38,58,42,68,32,47,72,43,59,76,61,88].map((h,i)=><span key={i} style={{height:h+'%'}}/> )}</div><svg viewBox="0 0 500 180" preserveAspectRatio="none"><polyline points="0,145 45,110 90,130 135,90 180,105 225,72 270,94 315,55 360,70 405,38 450,52 500,22"/><polyline points="0,155 45,130 90,140 135,118 180,126 225,105 270,112 315,88 360,92 405,68 450,72 500,55"/><polyline points="0,160 45,145 90,150 135,135 180,140 225,125 270,130 315,110 360,115 405,96 450,100 500,86"/></svg><div className="ref-axis">1 Okt　5 Okt　10 Okt　15 Okt　20 Okt　25 Okt　31 Okt</div></div><div className="ref-tower-mini">{[['Leads',Users],['Booking',CalendarDays],['Show Up',Users],['Cancel',AlertTriangle]].map(([t,I])=><div key={t}><I/><span><b>{t}</b><small>{empty}</small></span></div>)}</div></article><article className="ref-panel funnel"><Title icon={BarChart3} title="FUNNEL TRAVEL" sub="Perjalanan lead sampai keberangkatan"/><div className="ref-funnel-wrap"><div className="ref-funnel3d">{journey.map(([t,,c],i)=><div className={c} style={{width:(100-i*12)+'%'}} key={t}/>)}</div><div className="ref-journey">{journey.map(([t,I,c])=><div key={t} className={c}><I/><span><b>{t}</b><small>{empty}</small></span></div>)}</div></div></article></div>
 <div className="ref-mid-grid"><article className="ref-panel leads"><Title icon={Target} title="LEADS BERDASARKAN SOURCE" sub="Sumber leads dari platform iklan dan CRM"/><div className="ref-leads-body"><div className="ref-pie3d"/><div className="ref-source-list">{leadSources.map((x,i)=><div key={x}><i className={'c'+i}/><b>{x}</b><span>{empty}</span></div>)}</div></div></article><article className="ref-panel problems"><Title icon={AlertTriangle} title="LIMA MASALAH TERBESAR" sub="Berdasarkan data nyata dari seluruh divisi"/><div className="ref-problems">{[1,2,3,4,5].map((n,i)=><div key={n}><b>{n}</b><span>{empty}</span><em className={i===0?'danger':i<3?'warn':'monitor'}>{i===0?'Prioritas Tinggi':i<3?'Perlu Perhatian':'Monitoring'}</em></div>)}</div></article><article className="ref-panel decisions"><Title icon={AlertTriangle} title="KEPUTUSAN YANG MEMBUTUHKAN PERHATIAN" sub="Daftar isu penting yang memerlukan keputusan Owner"/><div className="ref-decisions">{[AlertTriangle,ClipboardList,Users,CircleDollarSign,Plane].map((I,i)=><div key={i}><I/><span>{empty}</span><b>›</b></div>)}</div></article></div>
 <div className="ref-bottom-grid"><article className="ref-panel reconciliation"><Title icon={GitCompareArrows} title="CROSS-DIVISION RECONCILIATION" sub="Perbandingan angka antar divisi untuk memastikan kesesuaian data"/><div className="ref-tabs"><b>Marketing vs CRM</b><span>Operasional vs Finance</span><span>Revenue vs Cost</span><span>Cabang vs Pusat</span><span>Agen vs Pusat</span></div><table><thead><tr><th>Indikator</th><th>Marketing</th><th>CRM</th><th>Selisih</th><th>Status</th></tr></thead><tbody>{['Leads','Booking','Show Up','Keberangkatan','Omzet'].map(x=><tr key={x}><td>{x}</td><td>{empty}</td><td>{empty}</td><td>-</td><td>-</td></tr>)}</tbody></table></article><article className="ref-panel alert-table"><Title icon={AlertTriangle} title="TABEL ALERT" sub="Daftar alert praktis berdasarkan data sistem"/><div className="ref-filter">Semua Divisi⌄</div><table><thead><tr><th>No</th><th>Tipe Alert</th><th>Deskripsi</th><th>Divisi</th><th>Status</th><th>Waktu</th><th>Aksi</th></tr></thead><tbody>{alerts.map(([a,d],i)=><tr key={a}><td>{i+1}</td><td>{a}</td><td>{empty}</td><td>{d}</td><td>{empty}</td><td>-</td><td><button>Detail</button></td></tr>)}</tbody></table></article></div>
 </section>}
