import React,{useMemo,useState} from 'react';
const configs={
'Dashboard Owner':{k:['Ringkasan Bisnis','Alert Aktif','Rekonsiliasi','Keputusan'],v:['Realtime','—','—','—'],f:['Jenis Alert/Keputusan','Divisi Terkait','Referensi Data','Prioritas','Keputusan/Tindak Lanjut','PIC','Batas Waktu','Status']},
'Manajer Marketing':{k:['Leads Bulan Ini','Conversion Rate','Revenue Marketing','Target Tercapai'],v:['1.248','18,6%','Rp 2,4 M','82%'],f:['Program/Kampanye','Jenis Aktivitas Online/Offline','Channel/Media','Cabang/Agen Terkait','Target Pasar','Target Leads/Penjualan','Budget','Leads Aktual','Booking/Closing','Revenue','Kemitraan/Komunitas','Evaluasi Campaign','Eskalasi Owner']},
'Manajer Operasional':{k:['Keberangkatan Aktif','Jamaah Siap','Issue Terbuka','SLA Operasional'],v:['4','184','7','94%'],f:['Grup/Keberangkatan','Tanggal Keberangkatan','Itinerary/Rencana Perjalanan','Tiket/Maskapai','Hotel/Akomodasi','Transportasi Lokal','Status Visa & Dokumen','Handling Bandara','Tour Leader/Muthawwif','Vendor Terkait','Kendala/Keluhan','Tindakan/Solusi','Status SOP & Kepatuhan','Evaluasi Vendor','Eskalasi Owner']},
'Manajer Finance':{k:['Cash In','Cash Out','Piutang','Collection Rate'],v:['Rp 3,8 M','Rp 2,1 M','Rp 640 Jt','91%'],f:['Tanggal Transaksi','Jenis Transaksi/Penerimaan/Pengeluaran','Jamaah/Vendor','Paket/Grup Keberangkatan','Nominal','Kategori/Akun','Cicilan/Pelunasan','Jatuh Tempo','Kas/Petty Cash','Costing/HPP Paket','Anggaran Grup','Bukti/Referensi Transaksi','Status Rekonsiliasi','Catatan Audit/Pelaporan']},
'CRM & Leads':{k:['Lead Baru','Qualified','Follow-up Hari Ini','Conversion'],v:['286','174','63','18,6%'],f:['Nama Calon Jamaah','No. WhatsApp','Sumber Lead','Minat Program','Status Lead','Respon Lead','Follow Up Terakhir','Follow Up Berikutnya','Status Booking','Treatment','Revenue','Voice of Jamaah/Keluhan','Bottleneck','Status Kelengkapan Dokumen','Status Pembayaran/Invoice','Grup Komunikasi','Status Alumni/Referral']},
'Digital Marketing & Ads':{k:['Ad Spend','Leads Ads','CPL','ROAS'],v:['Rp 86 Jt','742','Rp 116 rb','4,2x'],f:['Tanggal Laporan','Nama Campaign','Platform/Channel','Biaya Iklan','Leads','Booking','Show Up','Treatment','Revenue','ROAS','PIC','Evaluasi Campaign']},
'Marketing Offline':{k:['Event Aktif','Prospek','Closing','Cost/Lead'],v:['12','418','76','Rp 92 rb'],f:['Nama Aktivitas/Program','Jenis Aktivitas (Seminar/Pameran/Door-to-door)','Tanggal','Lokasi','PIC','Target Pasar','Target Prospek','Prospek Aktual','Booking/Closing','Biaya Aktivitas','Kemitraan/Komunitas','Hasil & Evaluasi']},
'Visa & Dokumen':{k:['Dokumen Diproses','Lengkap','Perlu Perbaikan','SLA'],v:['214','187','27','93%'],f:['Nama Jamaah','Paket/Grup Keberangkatan','Nomor Paspor','Masa Berlaku Paspor','Status KTP','Status KK','Status Buku Nikah','Status Vaksin/Sertifikat Kesehatan','Status Pengajuan Visa','Nomor/e-Visa','Status Tiket PP','Status Booking Hotel','Kelengkapan Dokumen','Catatan Verifikasi','Status Penyerahan Dokumen']},
'Inventory':{k:['Item Aktif','Stok Minimum','Distribusi','Akurasi Stok'],v:['128','9','436','98%'],f:['Nama Barang/Aset','Kategori','Stok Awal','Stock In','Stock Out','Stok Minimum','Expired Date','Pembelian','Pemakaian/Distribusi','Penerima/Grup Jamaah','Kuota/Deposit Non-fisik','Gudang/Lokasi','Hasil Stock Opname','Selisih Stok','Status Restock','Catatan']},
'Creative Performance':{k:['Konten Terbit','Engagement','Leads Konten','Winner'],v:['126','6,8%','384','12'],f:['Judul/Konten','Jenis/Format Konten','Platform','PIC Produksi','Status Produksi','Tanggal Publish','Engagement','Leads dari Konten','Catatan Performa Kreatif','Evaluasi/Tindak Lanjut']},
'Paket Haji':{k:['Paket Aktif','Kuota','Terjual','Occupancy'],v:['6','420','318','75,7%'],f:['Nama Paket','Harga','Kuota','Tanggal Berangkat']},
'Paket Umrah':{k:['Paket Aktif','Kuota','Terjual','Occupancy'],v:['18','960','742','77,3%'],f:['Nama Paket','Harga','Kuota','Tanggal Berangkat']},
'Booking & Pembayaran':{k:['Booking Aktif','Lunas','Outstanding','Payment Success'],v:['536','402','134','96,4%'],f:['Kode Booking','Nama Jamaah','Nominal','Status Pembayaran']},
'Daftar Jamaah':{k:['Jamaah Aktif','Data Lengkap','Belum Lengkap','Verified'],v:['1.842','1.691','151','91,8%'],f:['Nama Jamaah','WhatsApp','NIK/Paspor','Paket']},
'Jadwal Keberangkatan':{k:['Jadwal Aktif','H-30','H-7','Readiness'],v:['14','5','2','94%'],f:['Kode Grup','Tanggal','Bandara','Status']},
'Transportasi & Maskapai':{k:['Booking Transport','Tiket Issued','Pending','On-time'],v:['42','36','6','96%'],f:['Maskapai/Transport','Rute','Kode Booking','Status']},
'Akomodasi':{k:['Hotel Aktif','Room Nights','Confirmed','Pending'],v:['24','1.286','91%','9%'],f:['Nama Hotel','Kota','Check-in','Jumlah Kamar']},
'Konsumsi':{k:['Meal Plan','Porsi','Vendor Aktif','On-time'],v:['38','8.420','11','97%'],f:['Vendor','Tanggal','Jumlah Porsi','Jenis Menu']},
'Dokumen Perjalanan':{k:['Dokumen Terbit','Pending','Siap Distribusi','Akurasi'],v:['684','42','315','99%'],f:['Nama Jamaah','Jenis Dokumen','Nomor','Status']},
'Daftar Vendor':{k:['Vendor Aktif','Kontrak Aktif','Evaluasi Due','SLA Vendor'],v:['67','54','8','92%'],f:['Nama Vendor','Kategori','PIC','Status Kontrak']},
'Notifikasi & Broadcast':{k:['Broadcast','Delivered','Read Rate','Failed'],v:['48','96,8%','72%','3,2%'],f:['Judul Pesan','Audience','Channel','Jadwal Kirim']},
'Testimoni Jamaah':{k:['Testimoni Baru','Published','Rating','Response'],v:['86','64','4,8/5','94%'],f:['Nama Jamaah','Rating','Testimoni','Status Publikasi']},
'Galeri Video & Foto':{k:['Asset Baru','Published','Terpakai','Storage'],v:['428','286','71%','68%'],f:['Judul Asset','Kategori','Event','Status']},
'Alumni & Referral':{k:['Alumni Aktif','Referral','Closing Referral','Referral Rate'],v:['3.420','286','74','21%'],f:['Nama Alumni','WhatsApp','Nama Referral','Status']},
'Setting':{k:['User Aktif','Role','Cabang/Agen','Audit Event'],v:['186','12','74','1.284'],f:['Nama Pengguna','Role','Unit','Status Akses']}
};
const fallback={k:['Data Aktif','Target Bulan Ini','Progress','SLA'],v:['—','—','0%','—'],f:['Nama/Referensi','PIC','Target/Tanggal','Status']};
export default function ModulePage({title,description}){const c=configs[title]||fallback;const [saved,setSaved]=useState(false);const fields=useMemo(()=>c.f,[title]);return <section className="content module-v9"><div className="date">MDD TRAVEL • PERFORMANCE & OPERATIONS</div><div className="hello"><div><h1>{title}</h1><p>{description}</p></div></div><div className="module-kpis">{c.k.map((x,i)=><article className="module-kpi" key={x}><small>{x}</small><strong>{c.v[i]}</strong><span>Monitoring realtime</span></article>)}</div><article className="panel"><h3>Form Input {title}</h3><p className="muted">Pencatatan data operasional sesuai fungsi dan tanggung jawab {title}.</p><form className="module-form" onSubmit={e=>{e.preventDefault();setSaved(true);setTimeout(()=>setSaved(false),1800)}}>{fields.map((f,i)=><label key={f}>{f}<input required={i<2} placeholder={`Masukkan ${f.toLowerCase()}`}/></label>)}<button className="module-save">Simpan Data</button>{saved&&<span className="save-ok">✓ Data prototype tersimpan</span>}</form></article><article className="panel module-table"><div className="table-head"><div><h3>Aktivitas & Monitoring</h3><p className="muted">Struktur siap dihubungkan ke API/PostgreSQL pada tahap backend.</p></div><button>+ Tambah Data</button></div><div className="table-wrap"><table><thead><tr><th>Referensi</th><th>Aktivitas</th><th>PIC</th><th>Status</th><th>Update</th></tr></thead><tbody><tr><td>#MDD-001</td><td>{title} — aktivitas prioritas</td><td>Tim {title}</td><td><span className="status-pill">On Track</span></td><td>Hari ini</td></tr><tr><td>#MDD-002</td><td>Review data & tindak lanjut</td><td>Manager</td><td><span className="status-pill warn">Review</span></td><td>Hari ini</td></tr></tbody></table></div></article></section>}