import React,{useMemo,useState} from 'react';
const configs={
'Manajer Marketing':{k:['Leads Bulan Ini','Conversion Rate','Revenue Marketing','Target Tercapai'],v:['1.248','18,6%','Rp 2,4 M','82%'],o:['Meningkatkan qualified leads 25%','Menaikkan conversion menjadi 22%','Menjaga CAC sesuai target'],f:['Program/Kampanye','PIC','Target Leads','Budget']},
'Manajer Operasional':{k:['Keberangkatan Aktif','Jamaah Siap','Issue Terbuka','SLA Operasional'],v:['4','184','7','94%'],o:['100% readiness H-7','Issue kritis selesai <24 jam','Zero missed service'],f:['Kegiatan Operasional','PIC','Tanggal','Status']},
'Manajer Finance':{k:['Cash In','Cash Out','Piutang','Collection Rate'],v:['Rp 3,8 M','Rp 2,1 M','Rp 640 Jt','91%'],o:['Collection rate ≥95%','Rekonsiliasi harian 100%','Outstanding >30 hari turun 30%'],f:['Jenis Transaksi','Nominal','Akun/Kategori','Tanggal']},
'CRM & Leads':{k:['Lead Baru','Qualified','Follow-up Hari Ini','Conversion'],v:['286','174','63','18,6%'],o:['Response lead <5 menit','Follow-up coverage 100%','Conversion ≥22%'],f:['Nama Lead','WhatsApp','Sumber Lead','Tahap Pipeline']},
'Digital Marketing & Ads':{k:['Ad Spend','Leads Ads','CPL','ROAS'],v:['Rp 86 Jt','742','Rp 116 rb','4,2x'],o:['ROAS ≥4,5x','CPL turun 10%','Creative winner ≥3/bulan'],f:['Nama Campaign','Platform','Budget','Objective']},
'Marketing Offline':{k:['Event Aktif','Prospek','Closing','Cost/Lead'],v:['12','418','76','Rp 92 rb'],o:['Prospek event +20%','Closing rate ≥20%','Database event 100% tercatat'],f:['Nama Aktivitas','Lokasi','PIC','Target Prospek']},
'Visa & Dokumen':{k:['Dokumen Diproses','Lengkap','Perlu Perbaikan','SLA'],v:['214','187','27','93%'],o:['Kelengkapan H-21 100%','Error dokumen <2%','SLA verifikasi <24 jam'],f:['Nama Jamaah','Jenis Dokumen','Nomor Dokumen','Status']},
'Inventory':{k:['Item Aktif','Stok Minimum','Distribusi','Akurasi Stok'],v:['128','9','436','98%'],o:['Stockout 0 item kritis','Akurasi ≥99%','Audit stok bulanan 100%'],f:['Nama Barang','Jumlah','Gudang','Status']},
'Paket Haji':{k:['Paket Aktif','Kuota','Terjual','Occupancy'],v:['6','420','318','75,7%'],o:['Occupancy ≥90%','Margin sesuai target','Itinerary H-60 final'],f:['Nama Paket','Harga','Kuota','Tanggal Berangkat']},
'Paket Umrah':{k:['Paket Aktif','Kuota','Terjual','Occupancy'],v:['18','960','742','77,3%'],o:['Occupancy ≥90%','Paket unggulan ≥3','Margin paket terjaga'],f:['Nama Paket','Harga','Kuota','Tanggal Berangkat']},
'Booking & Pembayaran':{k:['Booking Aktif','Lunas','Outstanding','Payment Success'],v:['536','402','134','96,4%'],o:['Payment success ≥98%','Outstanding turun 25%','Konfirmasi <10 menit'],f:['Kode Booking','Nama Jamaah','Nominal','Status Pembayaran']},
'Daftar Jamaah':{k:['Jamaah Aktif','Data Lengkap','Belum Lengkap','Verified'],v:['1.842','1.691','151','91,8%'],o:['Data lengkap 100% H-30','Duplikasi 0%','Validasi identitas 100%'],f:['Nama Jamaah','WhatsApp','NIK/Paspor','Paket']},
'Jadwal Keberangkatan':{k:['Jadwal Aktif','H-30','H-7','Readiness'],v:['14','5','2','94%'],o:['Readiness H-7 100%','Zero missed departure','Manifest final H-3'],f:['Kode Grup','Tanggal','Bandara','Status']},
'Transportasi & Maskapai':{k:['Booking Transport','Tiket Issued','Pending','On-time'],v:['42','36','6','96%'],o:['Tiket issued H-30','On-time ≥95%','Perubahan jadwal termonitor 100%'],f:['Maskapai/Transport','Rute','Kode Booking','Status']},
'Akomodasi':{k:['Hotel Aktif','Room Nights','Confirmed','Pending'],v:['24','1.286','91%','9%'],o:['Konfirmasi H-30 100%','Rooming list akurat 100%','Complaint <2%'],f:['Nama Hotel','Kota','Check-in','Jumlah Kamar']},
'Konsumsi':{k:['Meal Plan','Porsi','Vendor Aktif','On-time'],v:['38','8.420','11','97%'],o:['On-time ≥98%','Complaint makanan <2%','Diet khusus 100% terpenuhi'],f:['Vendor','Tanggal','Jumlah Porsi','Jenis Menu']},
'Dokumen Perjalanan':{k:['Dokumen Terbit','Pending','Siap Distribusi','Akurasi'],v:['684','42','315','99%'],o:['Dokumen H-7 100% siap','Error <1%','Distribusi tercatat 100%'],f:['Nama Jamaah','Jenis Dokumen','Nomor','Status']},
'Daftar Vendor':{k:['Vendor Aktif','Kontrak Aktif','Evaluasi Due','SLA Vendor'],v:['67','54','8','92%'],o:['Vendor score ≥90%','Kontrak valid 100%','Evaluasi tepat waktu 100%'],f:['Nama Vendor','Kategori','PIC','Status Kontrak']},
'Notifikasi & Broadcast':{k:['Broadcast','Delivered','Read Rate','Failed'],v:['48','96,8%','72%','3,2%'],o:['Delivery ≥98%','Read rate ≥75%','Failed <2%'],f:['Judul Pesan','Audience','Channel','Jadwal Kirim']},
'Creative Performance':{k:['Konten Terbit','Engagement','Leads Konten','Winner'],v:['126','6,8%','384','12'],o:['Engagement ≥7%','12 creative winner/bulan','Output sesuai kalender 100%'],f:['Judul Konten','Platform','Format','PIC']},
'Testimoni Jamaah':{k:['Testimoni Baru','Published','Rating','Response'],v:['86','64','4,8/5','94%'],o:['Rating ≥4,8','Publish ≥75% testimoni valid','Response complaint <24 jam'],f:['Nama Jamaah','Rating','Testimoni','Status Publikasi']},
'Galeri Video & Foto':{k:['Asset Baru','Published','Terpakai','Storage'],v:['428','286','71%','68%'],o:['Metadata 100% lengkap','Asset H+1 terunggah','Reuse asset ≥70%'],f:['Judul Asset','Kategori','Event','Status']},
'Alumni & Referral':{k:['Alumni Aktif','Referral','Closing Referral','Referral Rate'],v:['3.420','286','74','21%'],o:['Referral +25%','Closing referral ≥30%','Alumni engagement ≥40%'],f:['Nama Alumni','WhatsApp','Nama Referral','Status']},
'Setting':{k:['User Aktif','Role','Cabang/Agen','Audit Event'],v:['186','12','74','1.284'],o:['MFA admin 100%','Review akses bulanan','Audit log 100% aktif'],f:['Nama Pengguna','Role','Unit','Status Akses']}
};
const fallback={k:['Data Aktif','Target Bulan Ini','Progress','SLA'],v:['—','—','0%','—'],o:['Tetapkan target utama','Definisikan indikator hasil','Review progres mingguan'],f:['Nama/Referensi','PIC','Target/Tanggal','Status']};
export default function ModulePage({title,description}){const c=configs[title]||fallback;const [saved,setSaved]=useState(false);const fields=useMemo(()=>c.f, [title]);return <section className="content module-v9"><div className="date">MDD TRAVEL • PERFORMANCE & OPERATIONS</div><div className="hello"><div><h1>{title}</h1><p>{description}</p></div></div><div className="module-kpis">{c.k.map((x,i)=><article className="module-kpi" key={x}><small>{x}</small><strong>{c.v[i]}</strong><span>Monitoring realtime</span></article>)}</div><div className="module-grid"><article className="panel"><h3>OKR Divisi</h3><p className="muted">Objective & Key Results untuk periode berjalan.</p>{c.o.map((x,i)=><div className="okr-row" key={x}><div><b>KR {i+1}</b><span>{x}</span></div><progress max="100" value={[72,58,84][i]||65}/></div>)}</article><article className="panel"><h3>Input Operasional</h3><p className="muted">Form prototype untuk pencatatan aktivitas {title}.</p><form className="module-form" onSubmit={e=>{e.preventDefault();setSaved(true);setTimeout(()=>setSaved(false),1800)}}>{fields.map((f,i)=><label key={f}>{f}<input required={i<2} placeholder={`Masukkan ${f.toLowerCase()}`}/></label>)}<button className="module-save">Simpan Data</button>{saved&&<span className="save-ok">✓ Data prototype tersimpan</span>}</form></article></div><article className="panel module-table"><div className="table-head"><div><h3>Aktivitas & Monitoring</h3><p className="muted">Struktur siap dihubungkan ke API/PostgreSQL pada tahap backend.</p></div><button>+ Tambah Data</button></div><div className="table-wrap"><table><thead><tr><th>Referensi</th><th>Aktivitas</th><th>PIC</th><th>Status</th><th>Update</th></tr></thead><tbody><tr><td>#MDD-001</td><td>{title} — aktivitas prioritas</td><td>Tim {title}</td><td><span className="status-pill">On Track</span></td><td>Hari ini</td></tr><tr><td>#MDD-002</td><td>Review target & tindak lanjut</td><td>Manager</td><td><span className="status-pill warn">Review</span></td><td>Hari ini</td></tr></tbody></table></div></article></section>}