import React,{useState} from 'react'; import {Routes,Route,NavLink} from 'react-router-dom'; import {Home,Users,Package,ReceiptText,Menu as MenuIcon} from 'lucide-react'; import {UIProvider} from './context/UIContext';
import Sidebar from './components/Sidebar'; import Header from './components/Header'; import DashboardPage from './pages/DashboardPage'; import CrmPage from './pages/CrmPage'; import JamaahPage from './pages/JamaahPage'; import PaketPage from './pages/PaketPage'; import BookingPage from './pages/BookingPage'; import PembayaranPage from './pages/PembayaranPage'; import KeberangkatanPage from './pages/KeberangkatanPage'; import AgenPage from './pages/AgenPage'; import CabangPage from './pages/CabangPage'; import KeuanganPage from './pages/KeuanganPage'; import LaporanPage from './pages/LaporanPage'; import PengaturanPage from './pages/PengaturanPage'; import ModulePage from './components/ModulePage';
export default function App(){const [open,setOpen]=useState(false);return <UIProvider><div className="app"><Sidebar open={open} onNavigate={()=>setOpen(false)}/>{open&&<button className="scrim" aria-label="Tutup menu" onClick={()=>setOpen(false)}/>}<main><Header onMenu={()=>setOpen(v=>!v)}/><Routes><Route path="/" element={<DashboardPage/>}/><Route path="/crm" element={<CrmPage/>}/><Route path="/jamaah" element={<JamaahPage/>}/><Route path="/paket" element={<PaketPage/>}/><Route path="/booking" element={<BookingPage/>}/><Route path="/pembayaran" element={<PembayaranPage/>}/><Route path="/keberangkatan" element={<KeberangkatanPage/>}/><Route path="/agen" element={<AgenPage/>}/><Route path="/cabang" element={<CabangPage/>}/><Route path="/keuangan" element={<KeuanganPage/>}/><Route path="/laporan" element={<LaporanPage/>}/><Route path="/pengaturan" element={<PengaturanPage/>}/>
<Route path="/transaksi" element={<ModulePage title="Transaksi" description="Pusat transaksi Travel Umrah MDD."/>}/>
<Route path="/inventory" element={<ModulePage title="Inventory" description="Pengelolaan inventory dan kebutuhan operasional."/>}/>
<Route path="/hris" element={<ModulePage title="HRIS" description="Pengelolaan SDM Travel Umrah MDD."/>}/>
<Route path="/transportasi" element={<ModulePage title="Fasilitas Transportasi" description="Pengelolaan fasilitas transportasi jamaah."/>}/>
<Route path="/akomodasi" element={<ModulePage title="Akomodasi" description="Pengelolaan akomodasi perjalanan jamaah."/>}/>
<Route path="/konsumsi" element={<ModulePage title="Konsumsi" description="Pengelolaan konsumsi jamaah."/>}/>
<Route path="/dokumen" element={<ModulePage title="Dokumen Perjalanan" description="Pengelolaan dokumen perjalanan jamaah."/>}/>
<Route path="/kantor-utama" element={<ModulePage title="Kantor Utama" description="Informasi dan pengelolaan kantor utama."/>}/>
<Route path="/mitra" element={<ModulePage title="Mitra Travel MDD" description="Pengelolaan jaringan mitra Travel MDD."/>}/>
<Route path="/calon-jamaah" element={<ModulePage title="Calon Jamaah" description="Database dan proses calon jamaah."/>}/>
<Route path="/alumni" element={<ModulePage title="Alumni Jamaah" description="Database alumni jamaah."/>}/>
<Route path="/testimoni" element={<ModulePage title="Video Testimoni" description="Koleksi dan pengelolaan video testimoni."/>}/>
<Route path="/vendor" element={<ModulePage title="Vendor & Hotel" description="Pengelolaan vendor dan hotel."/>}/>
<Route path="/manajemen-dokumen" element={<ModulePage title="Manajemen Dokumen" description="Pusat dokumen Travel Umrah MDD."/>}/>
<Route path="/customer-service" element={<ModulePage title="Customer Service" description="Pusat layanan jamaah."/>}/>
<Route path="/broadcast" element={<ModulePage title="Notifikasi & Broadcast" description="Pengelolaan notifikasi dan broadcast."/>}/>
<Route path="/task-reminder" element={<ModulePage title="Task & Reminder" description="Pengelolaan tugas dan pengingat."/>}/>
<Route path="*" element={<ModulePage title="Halaman tidak ditemukan" description="Route ini belum menjadi bagian recovery Travel Umrah MDD."/>}/></Routes><nav className="mobile-bottom"><NavLink to="/"><Home/><span>Beranda</span></NavLink><NavLink to="/jamaah"><Users/><span>Jamaah</span></NavLink><NavLink to="/paket"><Package/><span>Paket</span></NavLink><NavLink to="/booking"><ReceiptText/><span>Booking</span></NavLink><button onClick={()=>setOpen(true)}><MenuIcon/><span>Menu</span></button></nav></main></div></UIProvider>}